"""
UI <-> Gateway API contract test (Phase 2 W2.4).

Every path the UI's gateway client (ui/src/lib/api-client.ts) calls
must exist in the gateway's OpenAPI specification. This permanently
prevents the endpoint-name-drift bug class found in the 2026 audit
(~30 phantom endpoints).

The spec of record is docs/api/openapi.json, regenerated by
scripts/export_openapi.py; a staleness check ensures it matches the
live app.
"""

import json
import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
CLIENT = REPO / "ui" / "src" / "lib" / "api-client.ts"
SPEC = REPO / "docs" / "api" / "openapi.json"

CALL_RE = re.compile(
    r"apiClient\.(get|post|put|delete|patch)\(\s*[`'\"]([^`'\"]+)[`'\"]"
)


def _client_calls():
    src = CLIENT.read_text()
    calls = []
    for method, path in CALL_RE.findall(src):
        # Template literals: ${expr} -> {param}
        norm = re.sub(r"\$\{[^}]+\}", "{param}", path)
        calls.append((method.upper(), norm))
    return sorted(set(calls))


def _spec_paths():
    spec = json.loads(SPEC.read_text())
    out = set()
    for path, methods in spec["paths"].items():
        # Normalize path params to a generic placeholder
        norm = re.sub(r"\{[^}]+\}", "{param}", path)
        for m in methods:
            out.add((m.upper(), norm))
    return out


def test_spec_exists():
    assert SPEC.exists(), (
        "docs/api/openapi.json missing - run scripts/export_openapi.py"
    )


def test_every_ui_call_exists_in_gateway_spec():
    spec_paths = _spec_paths()
    missing = [
        (m, p) for (m, p) in _client_calls() if (m, p) not in spec_paths
    ]
    assert not missing, (
        "UI calls endpoints absent from the gateway OpenAPI spec "
        f"(drift!): {missing}. Either add the route to the gateway and "
        "re-run scripts/export_openapi.py, or fix the client path."
    )


def test_spec_is_not_stale():
    """The committed spec must match the live FastAPI app."""
    import os
    import sys

    os.environ.setdefault("AUTH_MODE", "optional")
    sys.path.insert(0, str(REPO / "services/api-gateway/src"))
    sys.path.insert(
        0, str(REPO / "services/api-gateway/src/gen/python/proto")
    )
    try:
        from main import app  # noqa: E402
    except Exception as exc:  # missing optional server deps on this host
        pytest.skip(f"gateway app not importable here: {exc}")

    live = {
        (m.upper(), re.sub(r"\{[^}]+\}", "{param}", p))
        for p, ms in app.openapi()["paths"].items()
        for m in ms
    }
    committed = _spec_paths()
    assert live == committed, (
        "docs/api/openapi.json is stale - run scripts/export_openapi.py "
        f"(diff: live-only={live - committed}, spec-only={committed - live})"
    )
